/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 large_bobtail.glb --transform 
Files: large_bobtail.glb [3.87MB] > /Users/aronhawkins/Documents/Projects/huck-application-rendering/large_bobtail-transformed.glb [359.47KB] (91%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/large_bobtail-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['1'].geometry} material={materials['Dark metal']} />
      <mesh geometry={nodes['2'].geometry} material={materials.Brass} />
    </group>
  )
}

useGLTF.preload('/large_bobtail-transformed.glb')
