/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 magnagrip.glb --transform 
Files: magnagrip.glb [1.1MB] > /Users/aronhawkins/Documents/Projects/huck-application-rendering/magnagrip-transformed.glb [74.42KB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/magnagrip-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['1'].geometry} material={materials['Brushed Steel']} />
    </group>
  )
}

useGLTF.preload('/magnagrip-transformed.glb')
