/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 BMT-R16-4.glb --transform 
Files: BMT-R16-4.glb [145.63KB] > /Users/aronhawkins/Documents/Projects/huck-application-rendering/BMT-R16-4-transformed.glb [14.49KB] (90%)
*/

import React from 'react';
import { useGLTF, useTexture } from '@react-three/drei';
import BoltFile from '../../public/BMT-R16-4-transformed.glb';
import BrushedMetalFile from '../../public/textures/brushed_metal.jpg';

export function BomtailBolt(props) {
  const { nodes, materials } = useGLTF(BoltFile);
  const texture = useTexture(BrushedMetalFile);
  return (
    <group {...props} dispose={null} ref={props.refs} castShadow={false} receiveShadow>
      <mesh geometry={nodes['BMT-R16-4'].geometry}>
        <meshStandardMaterial
          map={texture}
          metalness={1} // Full metal
          roughness={0.4} // Adjust for the brushed effect
          // color='silver' // Base color
        />
      </mesh>
    </group>
  );
}

useGLTF.preload(BoltFile);
