/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 large_bobtail_model.glb --transform 
Files: large_bobtail_model.glb [3.87MB] > /Users/aronhawkins/Documents/Projects/huck-application-rendering/large_bobtail_model-transformed.glb [359.47KB] (91%)
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import LargeBobtailFile from '../../public/large_bobtail_model-transformed.glb';

export function LargeBobtailBolt(props) {
  const { nodes, materials } = useGLTF(LargeBobtailFile);
  return (
    <group {...props} dispose={null} ref={props.refs}>
      <mesh geometry={nodes['1'].geometry} material={materials['Dark metal']} />
      <mesh geometry={nodes['2'].geometry} material={materials.Brass} />
    </group>
  );
}

useGLTF.preload(LargeBobtailFile);
