/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 magnagrip_model.glb --transform 
Files: magnagrip_model.glb [1.1MB] > /Users/aronhawkins/Documents/Projects/huck-application-rendering/magnagrip_model-transformed.glb [74.37KB] (93%)
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import MangagripFile from '../../public/magnagrip-transformed.glb';

export function MagnagripBolt(props) {
  const { nodes, materials } = useGLTF(MangagripFile);
  return (
    <group {...props} dispose={null} ref={props.refs} receiveShadow castShadow>
      <mesh geometry={nodes['1'].geometry} material={materials['Brushed Steel']} />
    </group>
  );
}

useGLTF.preload(MangagripFile);
