/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/Solar_Ground.glb 
*/

import React from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import SolarGroundFile from '../../public/Solar_Ground.glb';

export function SolarGround(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF(SolarGroundFile);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <mesh name='Plane' geometry={nodes.Plane.geometry} material={materials.coast_sand_01} position={[0, 0, 0]} scale={[0.6, 1, 0.6]} />
      </group>
    </group>
  );
}

useGLTF.preload(SolarGroundFile);
