/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/Solar.glb 
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import SolarFile from '../../public/Solar.glb';

export function Solar(props) {
  const { nodes, materials } = useGLTF(SolarFile);
  const ref = useRef(null);
  useEffect(() => {
    if (ref.current) {
      console.log(ref.current);
    }
  }, [ref]);
  return (
    <group ref={props.refs} {...props} dispose={null} scale={2} receiveShadow castShadow>
      <group name='Scene' receiveShadow castShadow>
        <mesh castShadow receiveShadow name='solar_panels002' geometry={nodes.solar_panels002.geometry} material={materials['pbr ']} position={[0.097, 0.002, -0.001]} />
        <mesh
          castShadow
          receiveShadow
          name='solar_panels006'
          geometry={nodes.solar_panels006.geometry}
          material={materials['pbr ']}
          position={[-0.831, 2.084, 0.179]}
          rotation={[0.808, 0, 0]}
          ref={ref}
        />
      </group>
    </group>
  );
}

useGLTF.preload(SolarFile);
