/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/Solar.glb --transform 
Files: public/Solar.glb [5.76MB] > /Users/aronhawkins/Documents/Projects/huck-application-rendering/Solar-transformed.glb [455.06KB] (92%)
*/

import React from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import SolarFile from '../../public/Solar-transformed.glb';

export function Solar(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF(SolarFile);
  const { actions } = useAnimations(animations, group);
  return (
    <group {...props} dispose={null} ref={props.refs}>
      <group name='Scene'>
        <mesh name='solar_panels002' geometry={nodes.solar_panels002.geometry} material={materials['pbr ']} position={[0.097, 0.002, -0.001]} />
        <mesh name='solar_panels006' geometry={nodes.solar_panels006.geometry} material={materials['pbr ']} position={[-0.831, 2.084, 0.179]} rotation={[0.808, 0, 0]} />
      </group>
    </group>
  );
}

useGLTF.preload(SolarFile);
