/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/Solar_Ground.glb --transform 
Files: public/Solar_Ground.glb [6.86MB] > /Users/aronhawkins/Documents/Projects/huck-application-rendering/Solar_Ground-transformed.glb [538.05KB] (92%)
*/

import React from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function SolarGround(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF('/Solar_Ground-transformed.glb');
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <mesh name='Plane' geometry={nodes.Plane.geometry} material={materials.coast_sand_01} position={[-5.32, -0.042, 3.912]} scale={[0.6, 1, 0.6]} />
      </group>
    </group>
  );
}

useGLTF.preload('/Solar_Ground-transformed.glb');
