/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/Truck_Ground.glb --transform 
Files: public/Truck_Ground.glb [6.86MB] > /Users/aronhawkins/Documents/Projects/huck-application-rendering/Truck_Ground-transformed.glb [537.06KB] (92%)
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function TruckGround(props) {
  const { nodes, materials } = useGLTF('/Truck_Ground-transformed.glb');
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Ground.geometry} material={materials.coast_sand_01} position={[19.279, 0, -13.742]} rotation={[Math.PI, -1.466, Math.PI]} scale={[2000, 1, 2000]} />
    </group>
  );
}

useGLTF.preload('/Truck_Ground-transformed.glb');
