/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/Truck.glb 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import TruckFile from '../../public/Truck.glb';

export function Truck(props) {
  const { nodes, materials } = useGLTF(TruckFile);
  return (
    <group {...props} dispose={null} rotation={[0, -Math.PI / 1.85, 0]} castShadow receiveShadow ref={props.refs}>
      <group position={[0, 2.231, 10.015]} scale={0.025}>
        <group position={[-37, -66.238, 161.139]} scale={0.432}>
          <mesh castShadow receiveShadow geometry={nodes.Rear_Rim_005.geometry} material={materials['Chrome.030']} position={[12.533, -0.018, -0.08]} />
          <group position={[-9.129, 0, 0]}>
            <mesh castShadow receiveShadow geometry={nodes.Untitled030.geometry} material={materials['Rubber.001']} />
            <mesh castShadow receiveShadow geometry={nodes.Untitled030_1.geometry} material={materials['Sidewall.001']} />
          </group>
          <group position={[23.374, 0, 0]}>
            <mesh castShadow receiveShadow geometry={nodes.Untitled060.geometry} material={materials['Rubber.001']} />
            <mesh castShadow receiveShadow geometry={nodes.Untitled060_1.geometry} material={materials['Sidewall.001']} />
          </group>
        </group>
        <group position={[-37, -66.238, 211.943]} scale={0.432}>
          <mesh castShadow receiveShadow geometry={nodes.Rear_Rim_006.geometry} material={materials['Chrome.030']} position={[12.533, -0.018, -0.08]} />
          <group position={[-9.129, 0, 0]}>
            <mesh castShadow receiveShadow geometry={nodes.Untitled009.geometry} material={materials['Rubber.001']} />
            <mesh castShadow receiveShadow geometry={nodes.Untitled009_1.geometry} material={materials['Sidewall.001']} />
          </group>
          <group position={[23.374, 0, 0]}>
            <mesh castShadow receiveShadow geometry={nodes.Untitled.geometry} material={materials['Rubber.001']} />
            <mesh castShadow receiveShadow geometry={nodes.Untitled_1.geometry} material={materials['Sidewall.001']} />
          </group>
        </group>
        <group position={[37, -66.238, 161.139]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.432}>
          <mesh castShadow receiveShadow geometry={nodes.Rear_Rim_011.geometry} material={materials['Chrome.030']} position={[12.533, -0.018, -0.08]} />
          <group position={[-9.129, 0, 0]}>
            <mesh castShadow receiveShadow geometry={nodes.Untitled066.geometry} material={materials['Rubber.001']} />
            <mesh castShadow receiveShadow geometry={nodes.Untitled066_1.geometry} material={materials['Sidewall.001']} />
          </group>
          <group position={[23.374, 0, 0]}>
            <mesh castShadow receiveShadow geometry={nodes.Untitled062.geometry} material={materials['Rubber.001']} />
            <mesh castShadow receiveShadow geometry={nodes.Untitled062_1.geometry} material={materials['Sidewall.001']} />
          </group>
        </group>
        <group position={[37, -66.238, 211.943]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.432}>
          <mesh castShadow receiveShadow geometry={nodes.Rear_Rim_010.geometry} material={materials['Chrome.030']} position={[12.533, -0.018, -0.08]} />
          <group position={[-9.129, 0, 0]}>
            <mesh castShadow receiveShadow geometry={nodes.Untitled029.geometry} material={materials['Rubber.001']} />
            <mesh castShadow receiveShadow geometry={nodes.Untitled029_1.geometry} material={materials['Sidewall.001']} />
          </group>
          <group position={[23.374, 0, 0]}>
            <mesh castShadow receiveShadow geometry={nodes.Untitled056.geometry} material={materials['Rubber.001']} />
            <mesh castShadow receiveShadow geometry={nodes.Untitled056_1.geometry} material={materials['Sidewall.001']} />
          </group>
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.License_Plate_Trailer.geometry}
          material={materials.L_Plate}
          position={[0, -43.64, 326.052]}
          rotation={[3.117, 0, -Math.PI]}
          scale={[0.228, 0.209, 0.209]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Orange_Light.geometry}
          material={materials['Orange Light']}
          position={[-81.163, -38.752, 1.542]}
          rotation={[0, -1.571, 0]}
          scale={[0.091, 0.091, 0.088]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Red_Light.geometry}
          material={materials['Red Light']}
          position={[-81.163, -38.752, 1.542]}
          rotation={[0, -1.571, 0]}
          scale={[0.091, 0.091, 0.088]}
        />
        <group position={[56.422, -87.002, 210.804]} rotation={[0, 0, Math.PI]} scale={[-1.579, -1.012, -1.012]}>
          <mesh castShadow receiveShadow geometry={nodes.Untitled034.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Untitled034_1.geometry} material={materials['Chrome.030']} />
        </group>
        <group position={[51.701, 86.405, 305.503]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-1, -1.027, -1]}>
          <mesh castShadow receiveShadow geometry={nodes.Untitled023.geometry} material={materials['Matte Plastic']} />
          <mesh castShadow receiveShadow geometry={nodes.Untitled023_1.geometry} material={materials['White Paint']} />
          <mesh castShadow receiveShadow geometry={nodes.Untitled023_2.geometry} material={materials.signals} />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Trailer_Suspensions.geometry}
          material={materials.Plastic}
          position={[-34.476, -58.768, -75.342]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1.049, 0.993, 0.993]}
        />
        <group position={[0, -37.844, 2.197]} scale={[0.985, 1, 1]}>
          <mesh castShadow receiveShadow geometry={nodes.Untitled024.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Untitled024_1.geometry} material={materials['Aluminium.001']} />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.White_Ligt.geometry}
          material={materials['White Light']}
          position={[-82.22, -38.752, 1.542]}
          rotation={[0, -1.571, 0]}
          scale={[0.091, 0.091, 0.088]}
        />
      </group>
      <group position={[0, 2.079, 0.594]} scale={0.026}>
        <group position={[-34.202, -57.51, 124.906]} scale={[0.209, 0.2, 0.2]}>
          <group position={[-31.82, 102.503, 35.252]} scale={[0.085, 0.099, 0.099]}>
            <mesh castShadow receiveShadow geometry={nodes.Untitled054.geometry} material={materials.Rubber} />
            <mesh castShadow receiveShadow geometry={nodes.Untitled054_1.geometry} material={materials.Sidewall} />
          </group>
          <group position={[31.795, 102.503, 35.252]} scale={[0.085, 0.099, 0.099]}>
            <mesh castShadow receiveShadow geometry={nodes.Untitled051.geometry} material={materials.Rubber} />
            <mesh castShadow receiveShadow geometry={nodes.Untitled051_1.geometry} material={materials.Sidewall} />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.WheelRim3.geometry}
            material={materials['Chrome.030']}
            position={[25.177, -0.037, -0.166]}
            rotation={[2.199, 0, Math.PI / 2]}
            scale={[4.181, 3.454, 4.181]}
          />
        </group>
        <group position={[34.202, -57.51, 81.557]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.209, 0.2, 0.2]}>
          <group position={[-31.82, 102.503, 35.252]} scale={[0.085, 0.099, 0.099]}>
            <mesh castShadow receiveShadow geometry={nodes.Untitled039.geometry} material={materials.Rubber} />
            <mesh castShadow receiveShadow geometry={nodes.Untitled039_1.geometry} material={materials.Sidewall} />
          </group>
          <group position={[31.795, 102.504, 35.252]} scale={[0.085, 0.099, 0.099]}>
            <mesh castShadow receiveShadow geometry={nodes.Untitled037.geometry} material={materials.Rubber} />
            <mesh castShadow receiveShadow geometry={nodes.Untitled037_1.geometry} material={materials.Sidewall} />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.WheelRim1.geometry}
            material={materials['Chrome.030']}
            position={[25.177, -0.037, -0.166]}
            rotation={[2.199, 0, Math.PI / 2]}
            scale={[4.181, 3.454, 4.181]}
          />
        </group>
        <group position={[34.202, -57.51, 124.907]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.209, 0.2, 0.2]}>
          <group position={[31.795, 102.504, 35.252]} scale={[0.085, 0.099, 0.099]}>
            <mesh castShadow receiveShadow geometry={nodes.Untitled057.geometry} material={materials.Rubber} />
            <mesh castShadow receiveShadow geometry={nodes.Untitled057_1.geometry} material={materials.Sidewall} />
          </group>
          <group position={[-31.82, 102.503, 35.252]} scale={[0.085, 0.099, 0.099]}>
            <mesh castShadow receiveShadow geometry={nodes.Untitled044.geometry} material={materials.Rubber} />
            <mesh castShadow receiveShadow geometry={nodes.Untitled044_1.geometry} material={materials.Sidewall} />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.WheelRim2.geometry}
            material={materials['Chrome.030']}
            position={[25.177, -0.037, -0.166]}
            rotation={[2.199, 0, Math.PI / 2]}
            scale={[4.181, 3.454, 4.181]}
          />
        </group>
        <group position={[-34.202, -57.51, 81.557]} scale={[0.209, 0.2, 0.2]}>
          <group position={[-31.82, 102.503, 35.252]} scale={[0.085, 0.099, 0.099]}>
            <mesh castShadow receiveShadow geometry={nodes.Untitled033.geometry} material={materials.Rubber} />
            <mesh castShadow receiveShadow geometry={nodes.Untitled033_1.geometry} material={materials.Sidewall} />
          </group>
          <group position={[31.795, 102.504, 35.252]} scale={[0.085, 0.099, 0.099]}>
            <mesh castShadow receiveShadow geometry={nodes.Untitled013.geometry} material={materials.Rubber} />
            <mesh castShadow receiveShadow geometry={nodes.Untitled013_1.geometry} material={materials.Sidewall} />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.WheelRim4.geometry}
            material={materials['Chrome.030']}
            position={[25.177, -0.037, -0.166]}
            rotation={[2.199, 0, Math.PI / 2]}
            scale={[4.181, 3.454, 4.181]}
          />
        </group>
        <group position={[-39.683, -57.887, -107.594]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.368}>
          <group position={[5.384, 0, 0]}>
            <mesh castShadow receiveShadow geometry={nodes.Untitled064.geometry} material={materials.Plastic} />
            <mesh castShadow receiveShadow geometry={nodes.Untitled064_1.geometry} material={materials['Chrome.030']} />
          </group>
          <group position={[-4.929, 0, 0]}>
            <mesh castShadow receiveShadow geometry={nodes.Untitled043.geometry} material={materials.Rubber} />
            <mesh castShadow receiveShadow geometry={nodes.Untitled043_1.geometry} material={materials.Sidewall} />
          </group>
        </group>
        <group position={[39.683, -57.887, -107.594]} scale={0.368}>
          <group position={[5.384, 0, 0]}>
            <mesh castShadow receiveShadow geometry={nodes.Untitled006.geometry} material={materials.Plastic} />
            <mesh castShadow receiveShadow geometry={nodes.Untitled006_1.geometry} material={materials['Chrome.019']} />
          </group>
          <group position={[-4.929, 0, 0]}>
            <mesh castShadow receiveShadow geometry={nodes.Untitled016.geometry} material={materials.Rubber} />
            <mesh castShadow receiveShadow geometry={nodes.Untitled016_1.geometry} material={materials.Sidewall} />
          </group>
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Antennas.geometry} material={materials.Plastic} position={[-47.208, 26.615, -79.953]} scale={[0.155, 0.15, 0.15]} />
        <mesh castShadow receiveShadow geometry={nodes.Cabin.geometry} material={materials['Car Paint.040']} position={[-46.877, -3.092, 5.399]} rotation={[0, 0, Math.PI / 2]} scale={0.121} />
        <group position={[-46.877, -3.092, 5.399]} rotation={[0, 0, Math.PI / 2]} scale={0.121}>
          <mesh castShadow receiveShadow geometry={nodes.Untitled004.geometry} material={materials['Car Paint.028']} />
          <mesh castShadow receiveShadow geometry={nodes.Untitled004_1.geometry} material={materials.Plastic} />
        </group>
        <group position={[-46.877, -3.092, 5.399]} rotation={[0, 0, Math.PI / 2]} scale={0.121}>
          <mesh castShadow receiveShadow geometry={nodes.Untitled053.geometry} material={materials['Car Paint.018']} />
          <mesh castShadow receiveShadow geometry={nodes.Untitled053_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Untitled053_2.geometry} material={materials['Chrome.006']} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Exhaust_Pipes.geometry} material={materials['Chrome.018']} position={[33.92, -35.034, 19.003]} rotation={[Math.PI, 0, 0]} scale={-0.136} />
        <group position={[-37.397, -8.778, -16.658]} rotation={[0, 0, Math.PI / 2]} scale={0.106}>
          <mesh castShadow receiveShadow geometry={nodes.Untitled058.geometry} material={materials['Chrome.010']} />
          <mesh castShadow receiveShadow geometry={nodes.Untitled058_1.geometry} material={materials['Glass Clear.001']} />
        </group>
        <group position={[-0.051, -15.754, -148.019]} rotation={[-0.996, 0, Math.PI]} scale={-0.014}>
          <mesh castShadow receiveShadow geometry={nodes.Untitled022.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Untitled022_1.geometry} material={materials['Chrome.009']} />
        </group>
        <group position={[-46.877, -3.092, 5.399]} rotation={[0, 0, Math.PI / 2]} scale={0.121}>
          <mesh castShadow receiveShadow geometry={nodes.Untitled055.geometry} material={materials['Car Paint.026']} />
          <mesh castShadow receiveShadow geometry={nodes.Untitled055_1.geometry} material={materials['Chrome.014']} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Front_Grills.geometry} material={materials['Chrome.042']} position={[-46.877, -3.092, 5.399]} rotation={[0, 0, Math.PI / 2]} scale={0.121} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fuel_Tanks.geometry}
          material={materials['Chrome.040']}
          position={[30.698, -53.092, -3.778]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.172, 0.168, 0.168]}
        />
        <mesh castShadow receiveShadow geometry={nodes.Grills_Back.geometry} material={materials['Pure Black']} position={[-46.877, -3.092, 5.399]} rotation={[0, 0, Math.PI / 2]} scale={0.121} />
        <group position={[-46.877, -3.092, 5.399]} rotation={[0, 0, Math.PI / 2]} scale={0.121}>
          <mesh castShadow receiveShadow geometry={nodes.Untitled035.geometry} material={materials['Chrome.034']} />
          <mesh castShadow receiveShadow geometry={nodes.Untitled035_1.geometry} material={materials['Glass Clear.001']} />
          <mesh castShadow receiveShadow geometry={nodes.Untitled035_2.geometry} material={materials['Orange Chrome.038']} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Hood.geometry} material={materials['Car Paint.024']} position={[-46.877, -3.092, 5.399]} rotation={[0, 0, Math.PI / 2]} scale={0.121} />
        <mesh castShadow receiveShadow geometry={nodes.Interior.geometry} material={materials.Interior} position={[-49.741, 1.823, 208.04]} rotation={[0, 0, Math.PI / 2]} scale={0.111} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.License_Plate.geometry}
          material={materials['License Plate']}
          position={[-0.338, -62.045, 149.076]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={1.004}
        />
        <group position={[0, -50.376, -0.783]} scale={0.285}>
          <mesh castShadow receiveShadow geometry={nodes.Untitled015.geometry} material={materials['Car Paint.004']} />
          <mesh castShadow receiveShadow geometry={nodes.Untitled015_1.geometry} material={materials.Plastic} />
        </group>
        <group position={[37.75, -76.8, 22.077]} rotation={[0, 0, Math.PI]} scale={[-1.145, -0.881, -0.881]}>
          <mesh castShadow receiveShadow geometry={nodes.Untitled007.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Untitled007_1.geometry} material={materials['Chrome.015']} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Mudguard_Mirrors.geometry} material={materials['Chrome.002']} position={[-39.26, -20.194, -134.421]} rotation={[Math.PI / 2, 0, -Math.PI]} />
        <mesh castShadow receiveShadow geometry={nodes.Mudguards.geometry} material={materials.Plastic} position={[-24.49, -47.943, -104.922]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.121} />
        <mesh castShadow receiveShadow geometry={nodes.Radiator.geometry} material={materials.Radiator} position={[-0.228, -58.099, -145.024]} scale={0.121} />
        <group position={[-43.235, -20.75, 10.419]} scale={[0.175, 0.171, 0.171]}>
          <mesh castShadow receiveShadow geometry={nodes.Untitled001.geometry} material={materials.Blue} />
          <mesh castShadow receiveShadow geometry={nodes.Untitled001_1.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Untitled001_2.geometry} material={materials['Red.001']} />
          <mesh castShadow receiveShadow geometry={nodes.Untitled001_3.geometry} material={materials['Aluminium.042']} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Roof.geometry} material={materials['Car Paint.023']} position={[-46.877, -3.092, 5.399]} rotation={[0, 0, Math.PI / 2]} scale={0.121} />
        <group position={[-46.877, -3.092, 5.399]} rotation={[0, 0, Math.PI / 2]} scale={0.121}>
          <mesh castShadow receiveShadow geometry={nodes.Untitled061.geometry} material={materials['Car Paint.006']} />
          <mesh castShadow receiveShadow geometry={nodes.Untitled061_1.geometry} material={materials.Plastic} />
        </group>
        <group position={[-28.662, -3.14, -110.725]} rotation={[-1.018, 0.131, -2.918]} scale={-0.066}>
          <mesh castShadow receiveShadow geometry={nodes.Untitled038.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Untitled038_1.geometry} material={materials.Signals} />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roof_Windows.geometry}
          material={materials['Piano Black.012']}
          position={[-46.754, -1.691, 5.045]}
          rotation={[0, 0, Math.PI / 2]}
          scale={0.117}
        />
        <group position={[-53.441, 9.194, -72.589]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[0.121, 0.138, 0.121]}>
          <mesh castShadow receiveShadow geometry={nodes.Untitled010.geometry} material={materials['Car Paint.025']} />
          <mesh castShadow receiveShadow geometry={nodes.Untitled010_1.geometry} material={materials['Chrome.013']} />
          <mesh castShadow receiveShadow geometry={nodes.Untitled010_2.geometry} material={materials.Aluminium} />
        </group>
        <group position={[-45.613, -25.746, 23.766]} rotation={[1.571, 0.007, 1.575]} scale={[0.224, 0.121, 0.121]}>
          <mesh castShadow receiveShadow geometry={nodes.Untitled042.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Untitled042_1.geometry} material={materials.Signals} />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Side_Skirt_Part_1.geometry}
          material={materials['Car Paint.007']}
          position={[-46.877, -3.092, 5.399]}
          rotation={[0, 0, Math.PI / 2]}
          scale={0.121}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Side_Skirt_Part_2.geometry}
          material={materials['Car Paint.022']}
          position={[-46.877, -3.092, 5.399]}
          rotation={[0, 0, Math.PI / 2]}
          scale={0.121}
        />
        <group position={[-46.877, -3.092, 5.399]} rotation={[0, 0, Math.PI / 2]} scale={0.121}>
          <mesh castShadow receiveShadow geometry={nodes.Untitled059.geometry} material={materials.Plastic} />
          <mesh castShadow receiveShadow geometry={nodes.Untitled059_1.geometry} material={materials.Signals} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Stairs.geometry} material={materials['Metal Texture']} position={[-45.226, -43.956, 35.627]} scale={0.121} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Suspensions.geometry}
          material={materials.Plastic}
          position={[-29.193, -56.794, 90.382]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.889, 0.84, 0.84]}
        />
        <group position={[-2.84, -47.722, 149.756]} rotation={[Math.PI / 2, 0, 0]} scale={[0.098, 0.099, 0.099]}>
          <mesh castShadow receiveShadow geometry={nodes.Untitled005.geometry} material={materials.Red} />
          <mesh castShadow receiveShadow geometry={nodes.Untitled005_1.geometry} material={materials['Chrome.007']} />
          <mesh castShadow receiveShadow geometry={nodes.Untitled005_2.geometry} material={materials['Glass Clear']} />
          <mesh castShadow receiveShadow geometry={nodes.Untitled005_3.geometry} material={materials.GlassRed} />
          <mesh castShadow receiveShadow geometry={nodes.Untitled005_4.geometry} material={materials.Plastic} />
        </group>
        <group position={[-46.877, -3.092, 5.399]} rotation={[0, 0, Math.PI / 2]} scale={0.121}>
          <mesh castShadow receiveShadow geometry={nodes.Untitled008.geometry} material={materials['Piano Black.041']} />
          <mesh castShadow receiveShadow geometry={nodes.Untitled008_1.geometry} material={materials['Glass Tinted']} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Wiper_Blades.geometry} material={materials.Plastic} position={[4.873, 0.499, -95.26]} />
      </group>
    </group>
  );
}

useGLTF.preload(TruckFile);
