/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/Truck.glb --transform 
Files: public/Truck.glb [52.24MB] > /Users/aronhawkins/Documents/Projects/huck-application-rendering/Truck-transformed.glb [3.08MB] (94%)
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import TruckFile from '../../public/Truck-transformed.glb';

export function Truck(props) {
  const { nodes, materials } = useGLTF(TruckFile);
  return (
    <group {...props} dispose={null} ref={props.refs}>
      <mesh geometry={nodes.License_Plate_Trailer.geometry} material={materials.PaletteMaterial001} position={[0, 1.123, 18.297]} rotation={[3.117, 0, -Math.PI]} scale={[0.006, 0.005, 0.005]} />
      {/* <mesh geometry={nodes.Fog_Lights.geometry} material={materials.PaletteMaterial002} position={[-1.05, 1.9, 1.7]} rotation={[0, 0, Math.PI / 2]} scale={0.003} /> */}
      <mesh geometry={nodes.Mudguard_Mirrors.geometry} material={materials.PaletteMaterial001} position={[-1.036, 1.546, -1.75]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.026} />
      <mesh geometry={nodes.Windows.geometry} material={materials.PaletteMaterial003} position={[-1.1, 1.997, 1.85]} rotation={[0, 0, Math.PI / 2]} scale={0.003} />
    </group>
  );
}

useGLTF.preload(TruckFile);
