/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/Truck.glb 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import TruckFile from '../../public/Truck.glb';

export function Truck(props) {
  const { nodes, materials } = useGLTF(TruckFile);
  return (
    <group {...props} dispose={null} rotation={[0, -Math.PI / 1.85, 0]} position={[3, 0, 0]}>
      <mesh geometry={nodes.Ground.geometry} material={materials.coast_sand_01} position={[19.279, 0, -13.742]} rotation={[Math.PI, -1.466, Math.PI]} scale={[2000, 1, 2000]} />
    </group>
  );
}

useGLTF.preload(TruckFile);
