/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/Truck_Ground.glb 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import TruckGroundFile from '../../public/Truck_Ground.glb';

export function TruckGround(props) {
  const { nodes, materials } = useGLTF(TruckGroundFile);
  return (
    <group {...props} dispose={null} receiveShadow ref={props.refs}>
      <mesh geometry={nodes.Ground.geometry} material={materials.coast_sand_01} position={[0, 0, 0]} rotation={[Math.PI, -1.466, Math.PI]} scale={[1000, 1, 1000]} receiveShadow />
    </group>
  );
}

useGLTF.preload(TruckGroundFile);
